services:
  - type: web
    name: gs-intersect-api
    runtime: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: free
    healthCheckPath: /__docs__/
    envVars:
      - key: PORT
        value: 8000
